#!/bin/sh
set -e

tiddlywiki_script=$(readlink -f $(which tiddlywiki))

if [ -n "$NODE_MEM" ]; then
    # Based on rule of thumb from:
    # http://fiznool.com/blog/2016/10/01/running-a-node-dot-js-app-in-a-low-memory-environment/
    mem_node_old_space=$((($NODE_MEM*4)/5))
    NODEJS_V8_ARGS="--max_old_space_size=$mem_node_old_space $NODEJS_V8_ARGS"
fi

if [ ! -d /var/lib/tiddlywiki/mywiki ]; then
  /usr/bin/env node $NODEJS_V8_ARGS $tiddlywiki_script mywiki --init server

  mkdir /var/lib/tiddlywiki/mywiki/tiddlers
fi


# Start the tiddlywiki server
if [ -z "$USERNAME" ]; then
    echo "missing USERNAME env" ; exit 1
fi

if [ -z "$PASSWORD" ]; then
    echo "missing PASSWORD env" ; exit 1
fi

if [ ! -f /etc/tiddlywiki/cert/key.pem ] ; then
    echo "missing file /etc/tiddlywiki/cert/key.pem"
fi

if [ ! -f /etc/tiddlywiki/cert/server.pem ] ; then
    echo "missing file /etc/tiddlywiki/cert/server.pem"
fi

exec /usr/bin/env node $NODEJS_V8_ARGS $tiddlywiki_script mywiki \
  --listen \
  host=0.0.0.0 \
  port=8080 \
  username="$USERNAME" \
  password="${PASSWORD}" \
  tls-key=/etc/tiddlywiki/cert/key.pem \
  tls-cert=/etc/tiddlywiki/cert/server.crt \
  debug-level=${DEBUG_LEVEL-none}
